import { Inter } from 'next/font/google';
import Head from 'next/head';

import { Card } from '@/src/components/Card/Card';

const inter = Inter({ subsets: ['latin'] });

const Home = () => {
  console.info('Hello, Next.Js enjoyer!');

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/assets/favicon.ico' />
      </Head>
      <main role='main' data-testid='main'>
        <h2 className={inter.className}>
          Get started by editing&nbsp;<code>pages/index.js</code>
        </h2>
        <Card />
      </main>
    </>
  );
};

export default Home;
